CREATE TABLE IF NOT EXISTS user (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  city TEXT
);

CREATE TABLE IF NOT EXISTS opportunities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  time_commitment TEXT NOT NULL,
  description TEXT NOT NULL,
  cities TEXT NOT NULL,
  due_date TEXT,
  hidden INTEGER DEFAULT 0 
);
